리액트 서버컴포넌트의 포렌식 (24.05.26)
Wannabe-Woowa-Article/2024-fe-article pull request #2
Opened 2024-05-26 12:22 UTC by brgndyy

[편하게 보기](https://github.com/Wannabe-Woowa-Article/2024-fe-article/blob/brgndyy/May/article/The%20Forensics%20Of%20React%20Server%20Components%20(RSCs).md)

번역을 하다가 흐름이 이상한 부분에 대해서 의역을 해놓은 상태입니다.

내용을 읽다보면, `waterfall 요청` 이라던지, `rsc payload` 등 용어들이 등장하는데요.

이는 스터디 폴더에 따로 정리해보도록 할게요!

2024-05-29 00:34 UTC, soi-ha commented
파일명을 The-Forensics-Of-React-Server-Components-(RSCs)
이런 식으로 다른 사람들이랑 통일시키면 좋을 것 같아요!

2024-05-30 00:52 UTC, llqqssttyy requested changes

2024-05-30 00:52 UTC, llqqssttyy commented on May/article/The Forensics Of React Server Components (RSCs).md
> +# 리액트 서버 컴포넌트의 포렌식
제목의 의미가 '리액트 서버 컴포넌트 포렌식하기' 일까요, '리액트 서버 컴포넌트가 하는 포렌식'일까요?

아티클의 내용이 리액트 서버 컴포넌트의 렌더 프로세스를 톺아보는 것 같아서 전자가 아닐까 생각했는데, 제목을 처음 봤을 때 예상한 내용은 후자여서 의미를 조금 더 분명히 하는 제목이라면 좋을 것 같다는 생각이 들었어요!

2024-05-30 00:57 UTC, llqqssttyy commented
긴 글 번역 정말 수고하셨습니다 건디~
내용도 어려워서 쉽지 않았을 것 같아요💦
문장은 전반적으로 매끄러운 것 같고, 제목 번역 관련해서 코멘트를 남겼으니 가벼운 마음으로 검토해 주세요~

2024-05-31 05:46 UTC, brgndyy commented on May/article/The Forensics Of React Server Components (RSCs).md
> +# 리액트 서버 컴포넌트의 포렌식
짚어주셔서 감사합니다~ 수정사항 반영했어요!

2024-05-31 05:48 UTC, merged