useEffect의 콜백은 언제 실행 되는가? 페인트 전인가 후인가 ?
Wannabe-Woowa-Article/2024-fe-article pull request #23
Opened 2024-07-16 10:24 UTC by brgndyy

[편하게 보기](https://github.com/Wannabe-Woowa-Article/2024-fe-article/blob/brgndyy/July/article/When-do-useEffect()-callbacks-get-run%3F-Before-paint-or-after-paint%3F.md)

늦어서 죄송합니다..

useEffect 콜백의 실행 시점을 담은 글이에요! 

내부 구조를 담은 글이어서 사실 봐도봐도 이해가 되지는 않지만, 두고두고 보면 도움 될거 같아서 선택했습니다~!

2024-07-20 14:30 UTC, lurgi requested changes
건디 고생하셨습니다~
글 이해하는게 너무너무 너무 너무 너무 너무 너무 어렵네요 ㅠㅠ;
대충 이해하고 넘어가겠습니다 ㅠ
약간의 단어 수정 사항을 제안해보아요~

2024-07-20 14:30 UTC, lurgi commented on July/article/When-do-useEffect()-callbacks-get-run?-Before-paint-or-after-paint?.md
> +짧은 답변: 대부분의 경우 useEffect() 콜백은 페인트 후에 실행되지만 항상 그런 것은 아닙니다.
```suggestion
요약: 대부분의 경우 useEffect() 콜백은 페인트 후에 실행되지만 항상 그런 것은 아닙니다.
```

2024-07-20 14:30 UTC, lurgi commented on July/article/When-do-useEffect()-callbacks-get-run?-Before-paint-or-after-paint?.md
> +아래의 코드 스니펫의 결과는 어떻게 될까요 ?
```suggestion
아래의 코드 스니펫의 결과는 어떻게 될까요?
```

2024-07-21 02:16 UTC, brgndyy commented on July/article/When-do-useEffect()-callbacks-get-run?-Before-paint-or-after-paint?.md
> +짧은 답변: 대부분의 경우 useEffect() 콜백은 페인트 후에 실행되지만 항상 그런 것은 아닙니다.
감사해요 러기~ 반영했습니다!

2024-07-21 02:17 UTC, brgndyy commented on July/article/When-do-useEffect()-callbacks-get-run?-Before-paint-or-after-paint?.md
> +아래의 코드 스니펫의 결과는 어떻게 될까요 ?
이 또한 수정 완료!

2024-07-22 03:11 UTC, merged