Git-Flow vs GitHub-Flow
Wannabe-Woowa-Article/2024-fe-article pull request #28
Opened 2024-07-22 03:38 UTC by soi-ha

저번주에 Git 브랜칭 전략에 대해 수업을 듣게되어 좀 더 자세히 알아보고자 아티클을 찾아 번역했습니다~!
사실 브랜칭 전략 듣기 전에 이미 저희 팀은 GitHub-Flow로 정하긴 했었는데요.. 읽다보니 저희 팀의 브랜칭 전략은 GitHub-Flow와 Git-Flow를 짬뽕...?해서 한 느낌이네용.. 
뭐 각자 팀마다 맞는 걸로 변경시키면 되는 거니까 ~~~

2024-07-23 02:29 UTC, Jaymyong66 requested changes
간단한 리뷰를 남겼습니다~ 
저희 조도 git-flow에서 약간 변형한 형태로 사용 중인데, 각자의 상황에 맞게 쓰는게 가장 좋은 방법이라고 생각해요. (main - develop - dev/fe, dev/be - 각자의 브랜치)

고생하셨습니당!

2024-07-23 02:29 UTC, Jaymyong66 commented on July/article/Git-Flow-vs-GitHub-Flow.md
> +Git-Flow는 서로 다른 기능 간의 병렬 개발 요구를 해결하는 방법을 제공합니다. 기능을 개발하기 시작하면 master 브랜치에서 feature 브랜치를 생성합니다. 그런 다음 기능에 대한 모든 개발 작업은 이 feature 브랜치에서 수행됩니다. 기능 작업을 완료한 후에는 릴리스를 위한 주 코드 경로로 feature 브랜치를 다시 병합합니다.
글의 첫문장이 잘 안 읽혀서 다음과 같이 살짝 의역하면 어떨까요? 꼭 반영 안해도 될 것 같습니당
```suggestion
Git-Flow는 서로 다른 기능의 병렬적인 개발에 대한 요구를 해소하는 방법을 제공합니다. 기능을 개발하기 시작하면 master 브랜치에서 feature 브랜치를 생성합니다. 그런 다음 기능에 대한 모든 개발 작업은 이 feature 브랜치에서 수행됩니다. 기능 작업을 완료한 후에는 릴리스를 위한 main 코드 경로로 feature 브랜치를 다시 병합합니다.
```

2024-07-23 02:29 UTC, Jaymyong66 commented on July/article/Git-Flow-vs-GitHub-Flow.md
> +- 개발자들은 기능 개발을 완료하고 feature 브랜치에서 검증 중에 오류가 감지되지 않습니다. 그런 다음 기능 브랜치의 코드를 개발 브랜치에 병합합니다.
브랜치는 영어 단어로 통일하면 좋겠네요!
```suggestion
- 개발자들은 기능 개발을 완료하고 feature 브랜치에서 검증 중에 오류가 감지되지 않습니다. 그런 다음 feature 브랜치의 코드를 develop 브랜치에 병합합니다.
```

2024-07-23 02:29 UTC, Jaymyong66 commented on July/article/Git-Flow-vs-GitHub-Flow.md
> +Git-Flow와는 달리 GitHub-Flow는 릴리스 브랜치를 사용하지 않습니다. GitHub-Flow의 개념에 따르면 버전이 준비되면 바로 배포할 수 있습니다. 마찬가지로 GitHub-Flow는 hotfix가 사소한 기능 변경과 동일하다고 믿으며, 처리 방법도 유사해야 한다고 생각합니다.
위와 같은 이유로!
```suggestion
Git-Flow와는 달리 GitHub-Flow는 release 브랜치를 사용하지 않습니다. GitHub-Flow의 개념에 따르면 버전이 준비되면 바로 배포할 수 있습니다. 마찬가지로 GitHub-Flow는 hotfix가 사소한 기능 변경과 동일하다고 믿으며, 처리 방법도 유사해야 한다고 생각합니다.
```

2024-07-23 02:29 UTC, Jaymyong66 commented on July/article/Git-Flow-vs-GitHub-Flow.md
> +- 새 코드를 master 브랜치에 병합하려면 **코드 검토를 요청하기 위해 풀 요청을 시작**해야 합니다.
*사소*) 풀이 full 이라면? ㅋㅋㅋㅋㅋㅋㅋ
```suggestion
- 새 코드를 master 브랜치에 병합하려면 **코드 검토를 요청하기 위해 pull 요청을 시작**해야 합니다.
```

2024-07-28 15:11 UTC, soi-ha commented on July/article/Git-Flow-vs-GitHub-Flow.md
> +- 개발자들은 기능 개발을 완료하고 feature 브랜치에서 검증 중에 오류가 감지되지 않습니다. 그런 다음 기능 브랜치의 코드를 개발 브랜치에 병합합니다.
오... 한글로 한 부분이 있었네요?! 수정할게용

2024-07-29 02:48 UTC, merged