Axios vs. Fetch API: Selecting the Right Tool for HTTP Requests
Wannabe-Woowa-Article/2024-fe-article pull request #42
Opened 2024-08-05 04:00 UTC by soi-ha

현재 저희 팀은 fetch를 사용하고 있는데요.
프로젝트를 시작하기 전에 무작성 axios를 사용하려고 했던 점이 떠올랐습니다. 
그냥 다들 프로젝트에서 axios를 사용한다는 이유만으로요.
글을 선정할 때, 기술검토에 지니가 올린 axios가 필요한 이유가 떠올라서 그렇다면 axios와 fetch의 차이는 뭘까? 이것도 모르고 axios를 사용하려고 했다! 는게 떠올라서 한번 찾아봤습니당

[한눈에 읽기!](https://github.com/Wannabe-Woowa-Article/2024-fe-article/blob/soi-ha/Aug/article/Axios-vs-Fetch-API%3A-Selecting-the-Right-Tool-for-HTTP-Requests.md)

2024-08-10 05:23 UTC, llqqssttyy requested changes
좋은 글 감사합니다 소하~
axios가 이렇게 많은 기능을 가지고 있는지, fetch로 동일한 기능을 만들면 얼마나 많은 코드가 필요한지 알 수 있었어요.
코드 예시가 잘못된 부분이 있어서 RC 드립니다! 고치고 다시 말씀해주세요~

2024-08-10 05:23 UTC, llqqssttyy commented on Aug/article/Axios-vs-Fetch-API:-Selecting-the-Right-Tool-for-HTTP-Requests.md
> +	});
오 여기 fetch로 만드는 예시가 아니라 axios 예시예용!

2024-08-10 05:23 UTC, llqqssttyy commented on Aug/article/Axios-vs-Fetch-API:-Selecting-the-Right-Tool-for-HTTP-Requests.md
> +```
이건 그냥 제안인데, 들여쓰기가 tab이 아니라 띄어쓰기 2번이면 코드 가독성이 더 좋을 것 같아요!

2024-08-12 03:15 UTC, soi-ha commented on Aug/article/Axios-vs-Fetch-API:-Selecting-the-Right-Tool-for-HTTP-Requests.md
> +	});
헐 이제 알았네요 ^>^>

2024-08-12 03:15 UTC, soi-ha commented on Aug/article/Axios-vs-Fetch-API:-Selecting-the-Right-Tool-for-HTTP-Requests.md
> +```
다음부터 반영해보겠읍니다..

2024-08-12 03:18 UTC, merged